// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class AccesoEspecial
    {
        public AccesoEspecial()
        {
            PermisoAccesoEspecial = new HashSet<PermisoAccesoEspecial>();
        }

        [Key]
        [Column("AccEspecialID")]
        public int AccEspecialId { get; set; }
        [StringLength(50)]
        public string Descripcion { get; set; }

        [InverseProperty("AccEspecial")]
        public virtual ICollection<PermisoAccesoEspecial> PermisoAccesoEspecial { get; set; }
    }
}