// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class AplicacionModulo
    {
        public AplicacionModulo()
        {
            AplicacionLicenciaModulo = new HashSet<AplicacionLicenciaModulo>();
        }

        [Key]
        [Column("ModuloID")]
        public short ModuloId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Required]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column(TypeName = "money")]
        public decimal PrecioDolar { get; set; }

        [InverseProperty("ModuloNavigation")]
        public virtual ICollection<AplicacionLicenciaModulo> AplicacionLicenciaModulo { get; set; }
    }
}