// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ArchivoModelo
    {
        [Key]
        [Column("ModeloArchivoID")]
        public short ModeloArchivoId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        public byte[] ModeloPlantilla { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string Extencion { get; set; }
        [Column("ClasificacionArchivoID")]
        public short? ClasificacionArchivoId { get; set; }
    }
}