// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class Banco
    {
        public Banco()
        {
            BancoSucursal = new HashSet<BancoSucursal>();
        }

        [Key]
        [Column("BancoID")]
        public int BancoId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Nombre { get; set; }
        public int CodigoBanco { get; set; }
        [Column("PaisID")]
        public short PaisId { get; set; }

        [InverseProperty("Banco")]
        public virtual ICollection<BancoSucursal> BancoSucursal { get; set; }
    }
}