// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    [Index("ComprobanteId", Name = "IX_ComprobanteTipoOperacionTipo_ComprobanteID")]
    [Index("TipoOperacionId", Name = "IX_ComprobanteTipoOperacionTipo_TipoOperacionID")]
    public partial class ComprobanteTipoOperacionTipo
    {
        public ComprobanteTipoOperacionTipo()
        {
            ImpuestoEmisionComprobante = new HashSet<ImpuestoEmisionComprobante>();
        }

        [Column("ComprobanteID")]
        public short ComprobanteId { get; set; }
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        [Key]
        [Column("RegCompOperID")]
        public int RegCompOperId { get; set; }
        public byte[] Reporte { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string NombreArchivoReporte { get; set; }
        public bool? ControlTalonario { get; set; }
        public bool? CalculoImporte { get; set; }
        public byte? TipoAjusteDefault { get; set; }

        [ForeignKey("ComprobanteId")]
        [InverseProperty("ComprobanteTipoOperacionTipo")]
        public virtual ComprobanteTipo Comprobante { get; set; }
        [ForeignKey("TipoOperacionId")]
        [InverseProperty("ComprobanteTipoOperacionTipo")]
        public virtual OperacionTipo TipoOperacion { get; set; }
        [InverseProperty("RegCompOper")]
        public virtual ICollection<ImpuestoEmisionComprobante> ImpuestoEmisionComprobante { get; set; }
    }
}