// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ComprobanteTipo
    {
        public ComprobanteTipo()
        {
            ComprobanteTipoOperacionTipo = new HashSet<ComprobanteTipoOperacionTipo>();
        }

        [Key]
        [Column("ComprobanteID")]
        public short ComprobanteId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string NombreComprobante { get; set; }
        [Column("ComprobanteIER")]
        public short? ComprobanteIer { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Abreviatura { get; set; }

        [InverseProperty("Comprobante")]
        public virtual ICollection<ComprobanteTipoOperacionTipo> ComprobanteTipoOperacionTipo { get; set; }
    }
}