// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ContabilidadIndiceAjusteInflacion
    {
        public short PeriodoAno { get; set; }
        public byte PeriodoMes { get; set; }
        [Key]
        [Column("RegID")]
        public int RegId { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal Indice { get; set; }
    }
}