// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class CultureInfo
    {
        [Key]
        [Column("PaisID")]
        public short PaisId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Culture { get; set; }
        [Required]
        [Column("ISO2Letras")]
        [StringLength(2)]
        [Unicode(false)]
        public string Iso2letras { get; set; }
        [Required]
        [Column("ISO3Letras")]
        [StringLength(3)]
        [Unicode(false)]
        public string Iso3letras { get; set; }
    }
}