// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class Empresa
    {
        public Empresa()
        {
            EmpresaUsuario = new HashSet<EmpresaUsuario>();
            LoginPermiso = new HashSet<LoginPermiso>();
        }

        [Key]
        [Column("EmpresaID")]
        public int EmpresaId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Required]
        [Column("DB_ConnectionString")]
        [StringLength(350)]
        [Unicode(false)]
        public string DbConnectionString { get; set; }
        [Column("DB_AlmaMobileConnectionString")]
        [StringLength(350)]
        [Unicode(false)]
        public string DbAlmaMobileConnectionString { get; set; }
        [Column("DB_AlmaODBC")]
        [StringLength(350)]
        [Unicode(false)]
        public string DbAlmaOdbc { get; set; }
        [StringLength(350)]
        [Unicode(false)]
        public string PadronEmpresaConnectionString { get; set; }
        public int? DiasNovedades { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LocalPassword { get; set; }
        [Column(TypeName = "xml")]
        public string Configuracion { get; set; }
        [StringLength(6)]
        [Unicode(false)]
        public string Abreviatura { get; set; }
        [StringLength(300)]
        [Unicode(false)]
        public string ManualProcedimientoLink { get; set; }
        public bool PermitePubicidad { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        [Column("ClienteID_DRR")]
        public int? ClienteIdDrr { get; set; }
        [StringLength(11)]
        [Unicode(false)]
        public string VersionAplicativo { get; set; }
        public byte? ImplementacionTipo { get; set; }
        public int? ContadorIngreso { get; set; }
        [Column("LicenciaID")]
        public int? LicenciaId { get; set; }
        public long? NroIdentificacion { get; set; }
        [Column("EmpresaTipoConfigID")]
        public short? EmpresaTipoConfigId { get; set; }
        public byte? TipoSincronizacion { get; set; }
        [Column("ServidorDDNS")]
        [StringLength(50)]
        [Unicode(false)]
        public string ServidorDdns { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("Empresa")]
        public virtual UsuarioAlmaNet AlmaUser { get; set; }
        [ForeignKey("LicenciaId")]
        [InverseProperty("Empresa")]
        public virtual AplicacionLicencia Licencia { get; set; }
        [InverseProperty("Empresa")]
        public virtual ICollection<EmpresaUsuario> EmpresaUsuario { get; set; }
        [InverseProperty("Empresa")]
        public virtual ICollection<LoginPermiso> LoginPermiso { get; set; }
    }
}