// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    [Index("EmpresaId", Name = "IX_EmpresaUsuario_EmpresaID")]
    public partial class EmpresaUsuario
    {
        [Column("EmpresaID")]
        public int EmpresaId { get; set; }
        [Column("AlmaUserID")]
        public int AlmaUserId { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("EmpresaUsuario")]
        public virtual UsuarioAlmaNet AlmaUser { get; set; }
        [ForeignKey("EmpresaId")]
        [InverseProperty("EmpresaUsuario")]
        public virtual Empresa Empresa { get; set; }
    }
}