// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ErrorMessage
    {
        [Key]
        [Column("ErrorID")]
        public int ErrorId { get; set; }
        public byte? Errortype { get; set; }
        public int? ErrorNro { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string MensajeError { get; set; }
        [Required]
        [Unicode(false)]
        public string Detalle { get; set; }
    }
}