// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class Form
    {
        public Form()
        {
            FormCampos = new HashSet<FormCampos>();
            PermisoForm = new HashSet<PermisoForm>();
        }

        [Key]
        [Column("FormID")]
        public int FormId { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string FormName { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Unicode(false)]
        public string Observaciones { get; set; }
        [Column(TypeName = "xml")]
        public string Configuracion { get; set; }
        public bool? EsAdicional { get; set; }

        [InverseProperty("Form")]
        public virtual ICollection<FormCampos> FormCampos { get; set; }
        [InverseProperty("Form")]
        public virtual ICollection<PermisoForm> PermisoForm { get; set; }
    }
}