// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ImpuestoPorZonaCompradorCategoria
    {
        [Column("CategoriaImpuestoID")]
        public byte CategoriaImpuestoId { get; set; }
        [Column("RegistroIDZonaComprador")]
        public int RegistroIdzonaComprador { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? Porcentaje { get; set; }

        [ForeignKey("CategoriaImpuestoId")]
        [InverseProperty("ImpuestoPorZonaCompradorCategoria")]
        public virtual ImpuestoCategoria CategoriaImpuesto { get; set; }
        [ForeignKey("RegistroIdzonaComprador")]
        [InverseProperty("ImpuestoPorZonaCompradorCategoria")]
        public virtual ImpuestoPorZonaComprador RegistroIdzonaCompradorNavigation { get; set; }
    }
}