// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ImpuestoPorEmisionComprobante
    {
        [Column("EmisionID")]
        public short EmisionId { get; set; }
        [Column("ImpuestoID")]
        public short ImpuestoId { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }

        [ForeignKey("EmisionId")]
        [InverseProperty("ImpuestoPorEmisionComprobante")]
        public virtual ImpuestoEmisionComprobante Emision { get; set; }
        [ForeignKey("ImpuestoId")]
        [InverseProperty("ImpuestoPorEmisionComprobante")]
        public virtual Impuesto Impuesto { get; set; }
    }
}