// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ImpuestoCodigoActividad
    {
        public ImpuestoCodigoActividad()
        {
            ImpuestoPorCodigoActividadComprador = new HashSet<ImpuestoPorCodigoActividadComprador>();
            ImpuestoPorCodigoActividadVendedor = new HashSet<ImpuestoPorCodigoActividadVendedor>();
        }

        [Key]
        [Column("CodigoActividadID")]
        public int CodigoActividadId { get; set; }
        [Required]
        [StringLength(160)]
        [Unicode(false)]
        public string DescripcionCodigoActividad { get; set; }

        [InverseProperty("CodigoActividad")]
        public virtual ICollection<ImpuestoPorCodigoActividadComprador> ImpuestoPorCodigoActividadComprador { get; set; }
        [InverseProperty("CodigoActividad")]
        public virtual ICollection<ImpuestoPorCodigoActividadVendedor> ImpuestoPorCodigoActividadVendedor { get; set; }
    }
}