// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ImpuestoCategoria
    {
        public ImpuestoCategoria()
        {
            ImpuestoEmisionComprobanteCompradorCategoriaImpuesto = new HashSet<ImpuestoEmisionComprobante>();
            ImpuestoEmisionComprobanteVendedorCategoriaImpuesto = new HashSet<ImpuestoEmisionComprobante>();
            ImpuestoPorZonaCompradorCategoria = new HashSet<ImpuestoPorZonaCompradorCategoria>();
            ImpuestoPorZonaVendedorCategoria = new HashSet<ImpuestoPorZonaVendedorCategoria>();
        }

        [Key]
        [Column("CategoriaImpuestoID")]
        public byte CategoriaImpuestoId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Required]
        [StringLength(3)]
        [Unicode(false)]
        public string Abreviatura { get; set; }
        [Column("CategoriaImpuestoIDER")]
        public byte? CategoriaImpuestoIder { get; set; }

        [InverseProperty("CompradorCategoriaImpuesto")]
        public virtual ICollection<ImpuestoEmisionComprobante> ImpuestoEmisionComprobanteCompradorCategoriaImpuesto { get; set; }
        [InverseProperty("VendedorCategoriaImpuesto")]
        public virtual ICollection<ImpuestoEmisionComprobante> ImpuestoEmisionComprobanteVendedorCategoriaImpuesto { get; set; }
        [InverseProperty("CategoriaImpuesto")]
        public virtual ICollection<ImpuestoPorZonaCompradorCategoria> ImpuestoPorZonaCompradorCategoria { get; set; }
        [InverseProperty("CategoriaImpuesto")]
        public virtual ICollection<ImpuestoPorZonaVendedorCategoria> ImpuestoPorZonaVendedorCategoria { get; set; }
    }
}