// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ImpuestoPorCodigoActividadVendedor
    {
        [Column("CodigoActividadID")]
        public int CodigoActividadId { get; set; }
        [Column("ImpuestoID")]
        public short ImpuestoId { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? Porcentaje { get; set; }

        [ForeignKey("CodigoActividadId")]
        [InverseProperty("ImpuestoPorCodigoActividadVendedor")]
        public virtual ImpuestoCodigoActividad CodigoActividad { get; set; }
        [ForeignKey("ImpuestoId")]
        [InverseProperty("ImpuestoPorCodigoActividadVendedor")]
        public virtual Impuesto Impuesto { get; set; }
    }
}