// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ImpuestoBaseImponible
    {
        [Key]
        [Column("ImpuestoBaseID")]
        public int ImpuestoBaseId { get; set; }
        [Column("ImpuestoID")]
        public short ImpuestoId { get; set; }
        [Column("ImpuestoRelID")]
        public short ImpuestoRelId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Formula { get; set; }

        [ForeignKey("ImpuestoId")]
        [InverseProperty("ImpuestoBaseImponible")]
        public virtual Impuesto Impuesto { get; set; }
    }
}