// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ImpuestoPorZonaComprador
    {
        public ImpuestoPorZonaComprador()
        {
            ImpuestoPorZonaCompradorCategoria = new HashSet<ImpuestoPorZonaCompradorCategoria>();
        }

        [Column("ImpuestoID")]
        public short ImpuestoId { get; set; }
        [Column("ZonaImpuestoID")]
        public short ZonaImpuestoId { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? Porcentaje { get; set; }

        [ForeignKey("ImpuestoId")]
        [InverseProperty("ImpuestoPorZonaComprador")]
        public virtual Impuesto Impuesto { get; set; }
        [ForeignKey("ZonaImpuestoId")]
        [InverseProperty("ImpuestoPorZonaComprador")]
        public virtual ImpuestoZona ZonaImpuesto { get; set; }
        [InverseProperty("RegistroIdzonaCompradorNavigation")]
        public virtual ICollection<ImpuestoPorZonaCompradorCategoria> ImpuestoPorZonaCompradorCategoria { get; set; }
    }
}