// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    /// <summary>
    /// Permite desglosar la aplicacion del impuesto segun categorias especificadas o Regimen a Aplicar ejem Ret. Ganacia RG 3884
    /// </summary>
    [Index("ImpuestoId", "ImpDesgId", Name = "IX_ImpuestoDesglose", IsUnique = true)]
    public partial class ImpuestoDesglose
    {
        [Column("ImpDesgID")]
        public byte ImpDesgId { get; set; }
        [Column("ImpuestoID")]
        public short ImpuestoId { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string DenominacionAdicional { get; set; }
        /// <summary>
        /// Indica Codigo Adic. Ejem. Nro Regimen
        /// </summary>
        public short CodigAdic { get; set; }
        /// <summary>
        /// Monto Minimo que tiene que tener El resultado de la Exprecion de la base Imponible para aplicar el impuesto
        /// </summary>
        [Column(TypeName = "money")]
        public decimal? MontoMinimo { get; set; }
        /// <summary>
        /// Porcentaje utilizado para calcular el importe del impuesto sobre la Base imponible
        /// </summary>
        [Column(TypeName = "decimal(15, 3)")]
        public decimal? PocentajeDeducir { get; set; }
        /// <summary>
        /// Importe  del Impuesto (Es fijo y no refiere a un calculo)
        /// </summary>
        [Column(TypeName = "money")]
        public decimal? ImpoteDeducir { get; set; }
        /// <summary>
        /// Monto Acumulado que tiene que tener la base imponible (refiere a que puede ser en varios comprobantes ) el Impuesto es aplicable cuandu el Monto acumulado del Impuesto supera el valor ingresado
        /// </summary>
        [Column(TypeName = "money")]
        public decimal? MontoAcumulado { get; set; }
        /// <summary>
        /// Indica a partir de que mes se resetea el Monto Acumulado
        /// </summary>
        public bool? ReseteaMensualmente { get; set; }
        /// <summary>
        /// -No aplicable
        /// </summary>
        public bool? ReseteaAnualmente { get; set; }
        /// <summary>
        /// Indica si el impuesta se suma al Total del Comprobante o al Total del Item
        /// </summary>
        public bool SumaAlTotal { get; set; }
        [Column(TypeName = "money")]
        public decimal? MontoMaximo { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }

        [ForeignKey("ImpuestoId")]
        [InverseProperty("ImpuestoDesglose")]
        public virtual Impuesto Impuesto { get; set; }
    }
}