// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class InstitucionBeneficencia
    {
        [Key]
        [Column("InstitucionBeneficienciaID")]
        public int InstitucionBeneficienciaId { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string RazonSocial { get; set; }
        public byte TipoNroIdentificacion { get; set; }
        public long NroIdentificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaAlta { get; set; }
        [Column("CategoriaImpuestoID")]
        public byte? CategoriaImpuestoId { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string PaginaWeb { get; set; }
        public byte[] Logo { get; set; }
        public byte[] Credencial { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Domicilio { get; set; }
        [StringLength(150)]
        public string Telefono { get; set; }
        [Column("BancoCBU")]
        [StringLength(22)]
        [Unicode(false)]
        public string BancoCbu { get; set; }
        [Column("BancoAliasCBU")]
        [StringLength(50)]
        [Unicode(false)]
        public string BancoAliasCbu { get; set; }
        [Column("BancoCBU2")]
        [StringLength(22)]
        [Unicode(false)]
        public string BancoCbu2 { get; set; }
        [Column("BancoAliasCBU2")]
        [StringLength(50)]
        [Unicode(false)]
        public string BancoAliasCbu2 { get; set; }
        [Column("ConfiguracionXML", TypeName = "xml")]
        public string ConfiguracionXml { get; set; }
    }
}