// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class LicenciaIndiceTabla
    {
        [Key]
        [Column("LicenciaID")]
        public short LicenciaId { get; set; }
        [Required]
        [StringLength(120)]
        [Unicode(false)]
        public string Tabla { get; set; }
        public int Contador { get; set; }
        [Required]
        [StringLength(160)]
        [Unicode(false)]
        public string CampoLlabe { get; set; }
        [Key]
        [Column("TableID")]
        public int TableId { get; set; }
    }
}