// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class Login
    {
        public Login()
        {
            LoginPermiso = new HashSet<LoginPermiso>();
            UsuarioAlmaNet = new HashSet<UsuarioAlmaNet>();
        }

        [Key]
        public int LoginId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string LoginName { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string LoginPassWord { get; set; }
        [Unicode(false)]
        public string Descripcion { get; set; }
        public byte AccesType { get; set; }
        [Column("DefaultEmpresaID")]
        public int? DefaultEmpresaId { get; set; }

        [InverseProperty("Login")]
        public virtual ICollection<LoginPermiso> LoginPermiso { get; set; }
        [InverseProperty("Login")]
        public virtual ICollection<UsuarioAlmaNet> UsuarioAlmaNet { get; set; }
    }
}