// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class LoginPermiso
    {
        [Column("LoginID")]
        public int LoginId { get; set; }
        [Column("PermisoID")]
        public int PermisoId { get; set; }
        [Key]
        [Column("RegistroID")]
        public long RegistroId { get; set; }
        [Column("EmpresaID")]
        public int? EmpresaId { get; set; }

        [ForeignKey("EmpresaId")]
        [InverseProperty("LoginPermiso")]
        public virtual Empresa Empresa { get; set; }
        [ForeignKey("LoginId")]
        [InverseProperty("LoginPermiso")]
        public virtual Login Login { get; set; }
        [ForeignKey("PermisoId")]
        [InverseProperty("LoginPermiso")]
        public virtual Permiso Permiso { get; set; }
    }
}