// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class MercadoPagoCuenta
    {
        [StringLength(150)]
        [Unicode(false)]
        public string Denominacion { get; set; }
        public byte? EntidadTipo { get; set; }
        public byte? PersonaTipo { get; set; }
        [Key]
        [Column("MercadoPagoID")]
        public int MercadoPagoId { get; set; }
        [Column("EMail")]
        [StringLength(150)]
        [Unicode(false)]
        public string Email { get; set; }
        public byte? TipoNroIdentificacion { get; set; }
        public long? NroIdentificacion { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Telefono { get; set; }
        [StringLength(30)]
        public string Ciudad { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string CodigoArea { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Domicilio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaAlta { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string DetalleRegistro { get; set; }
    }
}