// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class Moroso
    {
        [Key]
        [Column("MorosoID")]
        public int MorosoId { get; set; }
        public byte TipoNroIdentificacion { get; set; }
        public long NroIdentificacion { get; set; }
        [Column("MorosidadTipoID")]
        public byte MorosidadTipoId { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string RazonSocial { get; set; }
        [Required]
        [Unicode(false)]
        public string DetalleDeuda { get; set; }
        public int? CiudadId { get; set; }

        [ForeignKey("CiudadId")]
        [InverseProperty("Moroso")]
        public virtual PaisProvinciaEstadoCiudad Ciudad { get; set; }
    }
}