// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    [Keyless]
    public partial class MuestreoVenta
    {
        [Column("RegID")]
        public int RegId { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string CodBarra { get; set; }
        public int? CiudadId { get; set; }
        public int EstadoProvinciaId { get; set; }
        public byte Año { get; set; }
        public byte Mes { get; set; }
        public byte Periodo { get; set; }
        [Column(TypeName = "decimal(14, 3)")]
        public decimal? Cantidad { get; set; }
        [Column(TypeName = "money")]
        public decimal? PrecioCompra { get; set; }
        [Column(TypeName = "money")]
        public decimal? PrecioVenta { get; set; }
    }
}