// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    /// <summary>
    /// Indica los ditintos tipos de Noticias por Canal
    /// </summary>
    public partial class NoticiaCanalTipo
    {
        /// <summary>
        /// Indica el Proveedor de RSS (Ejem. Clarin, Nacion, Etc)
        /// </summary>
        [Key]
        [Column("CanalNoticiaID")]
        public short CanalNoticiaId { get; set; }
        /// <summary>
        /// Indica el Tipo de Nocia (Ejem. Policial, Internacional, Economica, etc)
        /// </summary>
        [Key]
        [Column("NoticiaTipoID")]
        public short NoticiaTipoId { get; set; }
        [Column("CanalRSS")]
        [StringLength(150)]
        [Unicode(false)]
        public string CanalRss { get; set; }
        public byte? CantidadCargar { get; set; }
        public short? MinVigencia { get; set; }
        public short? TiempoActualizar { get; set; }
        public bool? Inhabilitar { get; set; }

        [ForeignKey("CanalNoticiaId")]
        [InverseProperty("NoticiaCanalTipo")]
        public virtual NoticiaCanal CanalNoticia { get; set; }
        [ForeignKey("NoticiaTipoId")]
        [InverseProperty("NoticiaCanalTipo")]
        public virtual NoticiaTipo NoticiaTipo { get; set; }
    }
}