// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class NoticiaTipo
    {
        public NoticiaTipo()
        {
            NoticiaCanalTipo = new HashSet<NoticiaCanalTipo>();
        }

        [Key]
        [Column("NoticiaTipoID")]
        public short NoticiaTipoId { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("NoticiaTipo")]
        public virtual ICollection<NoticiaCanalTipo> NoticiaCanalTipo { get; set; }
    }
}