// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class NoticiaCanal
    {
        public NoticiaCanal()
        {
            NoticiaCanalTipo = new HashSet<NoticiaCanalTipo>();
        }

        [Key]
        [Column("CanalNoticiaID")]
        public short CanalNoticiaId { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [StringLength(350)]
        [Unicode(false)]
        public string WebSite { get; set; }
        [StringLength(350)]
        [Unicode(false)]
        public string ConecctionString { get; set; }
        public bool? Inhabilitado { get; set; }

        [InverseProperty("CanalNoticia")]
        public virtual ICollection<NoticiaCanalTipo> NoticiaCanalTipo { get; set; }
    }
}