// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class PadronAfip
    {
        [Key]
        [Column("CUIT", TypeName = "numeric(11, 0)")]
        public decimal Cuit { get; set; }
        [Required]
        [StringLength(50)]
        public string RazonSocial { get; set; }
        [Required]
        [StringLength(2)]
        [Unicode(false)]
        public string ImpuestoGanancia { get; set; }
        [Required]
        [Column("ImpuestoIVA")]
        [StringLength(2)]
        [Unicode(false)]
        public string ImpuestoIva { get; set; }
        [Required]
        [StringLength(2)]
        [Unicode(false)]
        public string Monotributo { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string IntegranteSociedad { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string Empleador { get; set; }
        [Required]
        [StringLength(2)]
        [Unicode(false)]
        public string ActividadMonotributo { get; set; }
    }
}