// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class PaisProvinciaEstadoCiudad
    {
        public PaisProvinciaEstadoCiudad()
        {
            BancoSucursal = new HashSet<BancoSucursal>();
            Moroso = new HashSet<Moroso>();
        }

        [Key]
        public int CiudadId { get; set; }
        public int EstadoProvinciaId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string DescripcionCiudad { get; set; }
        [Required]
        [StringLength(25)]
        [Unicode(false)]
        public string AbreviaturaCiudad { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string CodigoPostalCiudad { get; set; }
        public bool? Inhabilitado { get; set; }
        public int? CodigoCiudadRenta { get; set; }
        public int? CodigoDepartRenta { get; set; }

        [ForeignKey("EstadoProvinciaId")]
        [InverseProperty("PaisProvinciaEstadoCiudad")]
        public virtual PaisProvinciaEstado EstadoProvincia { get; set; }
        [InverseProperty("Ciudad")]
        public virtual ICollection<BancoSucursal> BancoSucursal { get; set; }
        [InverseProperty("Ciudad")]
        public virtual ICollection<Moroso> Moroso { get; set; }
    }
}