// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class PaisCuit
    {
        [Key]
        [Column("PaisCuitID")]
        public short PaisCuitId { get; set; }
        [Column("PaisID")]
        public short PaisId { get; set; }
        [Column("CUITPais")]
        public long Cuitpais { get; set; }
        public byte CodTipoSujeto { get; set; }

        [ForeignKey("PaisId")]
        [InverseProperty("PaisCuit")]
        public virtual Pais Pais { get; set; }
    }
}