// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class Perfil
    {
        public Perfil()
        {
            UsuarioPerfil = new HashSet<UsuarioPerfil>();
        }

        [Key]
        [Column("PerfilID")]
        public int PerfilId { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        [Column(TypeName = "xml")]
        public string Configuracion { get; set; }
        [Column("EmpresaID")]
        public int? EmpresaId { get; set; }
        [Column("SectorID")]
        public short? SectorId { get; set; }
        [Column("ConexionODBC_Fox")]
        [StringLength(250)]
        [Unicode(false)]
        public string ConexionOdbcFox { get; set; }
        public short? ExeptoSector { get; set; }
        public short? ExeptoSucursal { get; set; }
        [Column(TypeName = "xml")]
        public string Configuracion2 { get; set; }

        [InverseProperty("Perfil")]
        public virtual ICollection<UsuarioPerfil> UsuarioPerfil { get; set; }
    }
}