// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class PermisosGenericos
    {
        [Column("PermisoID")]
        public int PermisoId { get; set; }
        [Column("AccesolID")]
        public short AccesolId { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }

        [ForeignKey("AccesolId")]
        [InverseProperty("PermisosGenericos")]
        public virtual AccesoAutorizacion Accesol { get; set; }
        [ForeignKey("PermisoId")]
        [InverseProperty("PermisosGenericos")]
        public virtual Permiso Permiso { get; set; }
    }
}