// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class Permiso
    {
        public Permiso()
        {
            LoginPermiso = new HashSet<LoginPermiso>();
            PermisoAccesoEspecial = new HashSet<PermisoAccesoEspecial>();
            PermisoForm = new HashSet<PermisoForm>();
            PermisoFormCampos = new HashSet<PermisoFormCampos>();
            PermisoReporte = new HashSet<PermisoReporte>();
            PermisoTable = new HashSet<PermisoTable>();
            PermisoWebForm = new HashSet<PermisoWebForm>();
            PermisosGenericos = new HashSet<PermisosGenericos>();
        }

        [Key]
        [Column("PermisoID")]
        public int PermisoId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        public byte PermisoType { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [Unicode(false)]
        public string Detalle { get; set; }

        [InverseProperty("Permiso")]
        public virtual ICollection<LoginPermiso> LoginPermiso { get; set; }
        [InverseProperty("Permiso")]
        public virtual ICollection<PermisoAccesoEspecial> PermisoAccesoEspecial { get; set; }
        [InverseProperty("Permiso")]
        public virtual ICollection<PermisoForm> PermisoForm { get; set; }
        [InverseProperty("Permiso")]
        public virtual ICollection<PermisoFormCampos> PermisoFormCampos { get; set; }
        [InverseProperty("Permiso")]
        public virtual ICollection<PermisoReporte> PermisoReporte { get; set; }
        [InverseProperty("Permiso")]
        public virtual ICollection<PermisoTable> PermisoTable { get; set; }
        [InverseProperty("Permiso")]
        public virtual ICollection<PermisoWebForm> PermisoWebForm { get; set; }
        [InverseProperty("Permiso")]
        public virtual ICollection<PermisosGenericos> PermisosGenericos { get; set; }
    }
}