// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class PermisoAccesoEspecial
    {
        [Column("AccEspecialID")]
        public int AccEspecialId { get; set; }
        [Column("PermisoID")]
        public int PermisoId { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        /// <summary>
        /// Ejem. Restriccion Modificacion Precios 0-Tdos Restingidos 1-Compra 2-Costos 4-Ventas 8-Listas de Precios 16-Bonificaciones 32-Descuentos
        /// </summary>
        public short? NivelAcceso { get; set; }

        [ForeignKey("AccEspecialId")]
        [InverseProperty("PermisoAccesoEspecial")]
        public virtual AccesoEspecial AccEspecial { get; set; }
        [ForeignKey("PermisoId")]
        [InverseProperty("PermisoAccesoEspecial")]
        public virtual Permiso Permiso { get; set; }
    }
}