// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class PermisoFormCampos
    {
        [Column("CamposID")]
        public int CamposId { get; set; }
        [Column("PermisoID")]
        public int PermisoId { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        public short TipoAcceso { get; set; }

        [ForeignKey("CamposId")]
        [InverseProperty("PermisoFormCampos")]
        public virtual FormCampos Campos { get; set; }
        [ForeignKey("PermisoId")]
        [InverseProperty("PermisoFormCampos")]
        public virtual Permiso Permiso { get; set; }
    }
}