// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class ProductoNroSerieDetalleTipoCalculos
    {
        [Key]
        [Column("CalculoID")]
        public short CalculoId { get; set; }
        public short? TipoMedida1 { get; set; }
        public short? TipoMedida2 { get; set; }
        public short? TipoMedida3 { get; set; }
        public short? TipoMedida4 { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Formula { get; set; }
        public short? TipoMedidaResult { get; set; }
    }
}