// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class Reporte
    {
        public Reporte()
        {
            PermisoReporte = new HashSet<PermisoReporte>();
            ReporteModificado = new HashSet<ReporteModificado>();
        }

        [Key]
        [Column("ReportID")]
        public int ReportId { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string ReportName { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        public bool UsoRestringido { get; set; }
        [Column("UtilzaRepModiID")]
        public int? UtilzaRepModiId { get; set; }

        [InverseProperty("Report")]
        public virtual ICollection<PermisoReporte> PermisoReporte { get; set; }
        [InverseProperty("Report")]
        public virtual ICollection<ReporteModificado> ReporteModificado { get; set; }
    }
}