// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class TableName
    {
        public TableName()
        {
            BuscarConfiguracion = new HashSet<BuscarConfiguracion>();
            PermisoTable = new HashSet<PermisoTable>();
        }

        [Key]
        [Column("TableID")]
        public int TableId { get; set; }
        [Required]
        [StringLength(80)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        public byte CatalogType { get; set; }
        [Column("SQL_ID")]
        public int SqlId { get; set; }

        [InverseProperty("Table")]
        public virtual ICollection<BuscarConfiguracion> BuscarConfiguracion { get; set; }
        [InverseProperty("Table")]
        public virtual ICollection<PermisoTable> PermisoTable { get; set; }
    }
}