// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class TransporteCubiertaCondicion
    {
        [Key]
        [Column("CondicionCubiertaID")]
        public int CondicionCubiertaId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Column(TypeName = "decimal(9, 2)")]
        public decimal PorcentajeEstado { get; set; }
    }
}