// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class TransporteTransmisionTipo
    {
        [Key]
        [Column("TransmisionTipoID")]
        public short TransmisionTipoId { get; set; }
        [Required]
        [StringLength(250)]
        public string Descripcion { get; set; }
    }
}