// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    /// <summary>
    /// Indica todos los Dispositivos Vinculardos a Este Usuario de Alma
    /// </summary>
    public partial class UsuarioAlmaMobile
    {
        /// <summary>
        /// UsuarioID en AlmaNET
        /// </summary>
        [Column("AlmaUserID")]
        public int AlmaUserId { get; set; }
        /// <summary>
        /// DispositivoID (autoicrementar)
        /// </summary>
        [Key]
        [Column("AlmaMobileID")]
        public int AlmaMobileId { get; set; }
        /// <summary>
        /// Nombre Usuario en El Dispositivo
        /// </summary>
        [StringLength(250)]
        public string NombreUsuario { get; set; }
        /// <summary>
        /// Contraseña dispositivo
        /// </summary>
        [StringLength(250)]
        public string Contraseña { get; set; }
        /// <summary>
        /// VendedorID Vinculado
        /// </summary>
        [Column("VendedorID")]
        public int? VendedorId { get; set; }
        /// <summary>
        /// Indica si solo sincroniza datos vinculados a este vendedor
        /// </summary>
        public bool? SoloDatosVendedor { get; set; }
        /// <summary>
        /// Nro Serie / Nro Unico para identificar el dsipositivo
        /// </summary>
        [StringLength(250)]
        public string NroSerieDispositivo { get; set; }
        /// <summary>
        /// Valor Binario 0-Todos 1-Con Stock 2-Pendiente Recibir  
        /// </summary>
        public int SoloConStock { get; set; }
        /// <summary>
        /// Indica q esta funcioando como DEMO
        /// </summary>
        public bool? EsDemo { get; set; }
        /// <summary>
        /// Indica la Fecha y hora q se utilizo 1era ves en el dispositivo
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? FechaHoraAlta { get; set; }
        /// <summary>
        /// 0- Indica todos los modulos (Valor binario para indicar q modulos se habilitaran )
        /// </summary>
        public int Modulos { get; set; }
        /// <summary>
        /// La idea es que se pueda saber cuando fue la ultima ves q se conecto para subir informacion (Pedidos, etc.)
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? SincronizacionSubida { get; set; }
        /// <summary>
        /// Ultima ves q se conecto para bajar informacion,registra el momento en que se actulizaron los datos en el cel  (ejem. Actulizacion PRecios)
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? SincronizacionBajada { get; set; }
        /// <summary>
        /// 10- Pedidos 20-Presupuesto 30-Facturacion directa
        /// </summary>
        public int? RegistraOperacionTipo { get; set; }
        /// <summary>
        /// nul 0- No realiza encuesta 1-Todas las Encuestas 10-Encuesta x cada Visita 20- Encuesta solo No Realizaron Pedidos 
        /// </summary>
        public byte? RealizaEncuesta { get; set; }
        public bool PermiteModificarPrecio { get; set; }
        /// <summary>
        /// Indico la Zona Asignada para trabajar (Vendedores), filtra en el dipositivo solo Clientes de esta Zona
        /// </summary>
        [Column("ZonaID")]
        public int? ZonaId { get; set; }
        /// <summary>
        /// Indico la RUTA  Asignada para trabajar (Vendedores), filtra en el dipositivo solo Clientes de esta RUTA
        /// </summary>
        [Column("RutaID")]
        public int? RutaId { get; set; }
        /// <summary>
        ///  indica que al vendedor se le mostrará únicamente los clientes de dicho día de visita
        /// </summary>
        public bool? SoloClientesDia { get; set; }
        /// <summary>
        /// para posibilitar que se asigne días adicionales de visitas
        /// </summary>
        public byte? DiasAdicionales { get; set; }
        [Column("URLServicio")]
        [StringLength(250)]
        [Unicode(false)]
        public string Urlservicio { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string BaseDatosEmpresa { get; set; }
        public byte? CantidadItems { get; set; }
        public bool PermiteModificarBonificacion { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string FiltraClasifProducto { get; set; }
        [Column("SectorID")]
        public short? SectorId { get; set; }
        [Column("SucursalID")]
        public short? SucursalId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("UsuarioAlmaMobile")]
        public virtual UsuarioAlmaNet AlmaUser { get; set; }
    }
}