// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    [Index("AlmaUserId", Name = "IX_UsuarioPerfil_AlmaUserIID")]
    [Index("PerfilId", Name = "IX_UsuarioPerfil_PerfilID")]
    public partial class UsuarioPerfil
    {
        [Column("AlmaUserID")]
        public int AlmaUserId { get; set; }
        [Column("PerfilID")]
        public int PerfilId { get; set; }
        [Key]
        [Column("UsuarioPerfilID")]
        public int UsuarioPerfilId { get; set; }
        public bool EsPerfilPredeterminado { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("UsuarioPerfil")]
        public virtual UsuarioAlmaNet AlmaUser { get; set; }
        [ForeignKey("PerfilId")]
        [InverseProperty("UsuarioPerfil")]
        public virtual Perfil Perfil { get; set; }
    }
}