// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    [Index("UserName", Name = "IX_UsuarioAlmaNet_UserName", IsUnique = true)]
    public partial class UsuarioAlmaNet
    {
        public UsuarioAlmaNet()
        {
            BuscarConfiguracion = new HashSet<BuscarConfiguracion>();
            Empresa = new HashSet<Empresa>();
            EmpresaUsuario = new HashSet<EmpresaUsuario>();
            UsuarioAlmaMobile = new HashSet<UsuarioAlmaMobile>();
            UsuarioAlmaNetAuditoria = new HashSet<UsuarioAlmaNetAuditoria>();
            UsuarioAlmaNetequipo = new HashSet<UsuarioAlmaNetequipo>();
            UsuarioPerfil = new HashSet<UsuarioPerfil>();
            UsuarioWeb = new HashSet<UsuarioWeb>();
        }

        [Column("LoginID")]
        public int? LoginId { get; set; }
        [Column("UserID")]
        public Guid? UserId { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string UserName { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string PassWord { get; set; }
        [Key]
        [Column("AlmaUserID")]
        public int AlmaUserId { get; set; }
        public bool IsEnabled { get; set; }
        public bool? IsAlmaMovileUser { get; set; }
        [Column("ForceSQLLogin")]
        public bool? ForceSqllogin { get; set; }
        [Column("UserIDSQL")]
        public int? UserIdsql { get; set; }
        [Column(TypeName = "xml")]
        public string Configuracion { get; set; }
        [Column("DefaultEmpresaID")]
        public int? DefaultEmpresaId { get; set; }
        public byte? RestringirAccion { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Email { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string PswEmail { get; set; }
        public short? RegistroAuditoria { get; set; }
        [StringLength(6)]
        [Unicode(false)]
        public string Abreviatura { get; set; }
        [Column("filer")]
        [StringLength(50)]
        [Unicode(false)]
        public string Filer { get; set; }
        public byte? ControlAcceso { get; set; }
        [Column("ServerSMTP")]
        [StringLength(150)]
        public string ServerSmtp { get; set; }
        [Column("PortSMTP")]
        public int? PortSmtp { get; set; }
        [Column("UseSMTPConSSL")]
        public bool? UseSmtpconSsl { get; set; }
        public bool? PuedeCambiarClave { get; set; }
        public short? DiasModificar { get; set; }
        [Column(TypeName = "date")]
        public DateTime? FechaAlta { get; set; }
        [StringLength(30)]
        public string VersionSelector { get; set; }

        [ForeignKey("LoginId")]
        [InverseProperty("UsuarioAlmaNet")]
        public virtual Login Login { get; set; }
        [InverseProperty("AlmaUser")]
        public virtual ICollection<BuscarConfiguracion> BuscarConfiguracion { get; set; }
        [InverseProperty("AlmaUser")]
        public virtual ICollection<Empresa> Empresa { get; set; }
        [InverseProperty("AlmaUser")]
        public virtual ICollection<EmpresaUsuario> EmpresaUsuario { get; set; }
        [InverseProperty("AlmaUser")]
        public virtual ICollection<UsuarioAlmaMobile> UsuarioAlmaMobile { get; set; }
        [InverseProperty("AlmaUser")]
        public virtual ICollection<UsuarioAlmaNetAuditoria> UsuarioAlmaNetAuditoria { get; set; }
        [InverseProperty("AlmaUser")]
        public virtual ICollection<UsuarioAlmaNetequipo> UsuarioAlmaNetequipo { get; set; }
        [InverseProperty("AlmaUser")]
        public virtual ICollection<UsuarioPerfil> UsuarioPerfil { get; set; }
        [InverseProperty("AlmaUser")]
        public virtual ICollection<UsuarioWeb> UsuarioWeb { get; set; }
    }
}