// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    [Index("AlmaUserId", "NombreEquipoLocal", "SesionId", "UsuarioNombre", Name = "ControlSalida")]
    public partial class UsuarioAlmaNetAuditoria
    {
        [Key]
        [Column("RegAuditID")]
        public int RegAuditId { get; set; }
        public byte TipoAudit { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaHoraIngreso { get; set; }
        [Column("AlmaUserID")]
        public int AlmaUserId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string UsuarioNombre { get; set; }
        public bool UtilizoEscritorioRemoto { get; set; }
        [Column("DireccionIPRemoto")]
        [StringLength(20)]
        [Unicode(false)]
        public string DireccionIpremoto { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string NombreEquipoLocal { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string NombreEquipoRemoto { get; set; }
        [Column("SesionID")]
        public short? SesionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaHoraSalida { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("UsuarioAlmaNetAuditoria")]
        public virtual UsuarioAlmaNet AlmaUser { get; set; }
    }
}