// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    /// <summary>
    /// Usuario AlmaNet q se concede permsiso Sobre el Servidor en la Nube
    /// </summary>
    [Table("UsuarioAlmaNETEquipo")]
    public partial class UsuarioAlmaNetequipo
    {
        [Key]
        [Column("UsuarioEquipoID")]
        public int UsuarioEquipoId { get; set; }
        /// <summary>
        /// Nombre usuario de Windows/Escritorio Remoto
        /// </summary>
        [StringLength(50)]
        public string UsuarioSistema { get; set; }
        [Column("AlmaUserID")]
        public int AlmaUserId { get; set; }
        public int? IdEquipo { get; set; }
        /// <summary>
        /// Permite Establecer dias y horarios
        /// </summary>
        [Column(TypeName = "xml")]
        public string CondicionConexion { get; set; }
        /// <summary>
        /// 0-No asigando, 1-Activado 10-Solicitado
        /// </summary>
        [Column("ActivacionEstadoID")]
        public byte? ActivacionEstadoId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("UsuarioAlmaNetequipo")]
        public virtual UsuarioAlmaNet AlmaUser { get; set; }
        [ForeignKey("IdEquipo")]
        [InverseProperty("UsuarioAlmaNetequipo")]
        public virtual EquipoEmpresa IdEquipoNavigation { get; set; }
    }
}