// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBAlmaNET.Models
{
    public partial class VersionLog
    {
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string VersionNumero { get; set; }
        [Required]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column(TypeName = "date")]
        public DateTime FechaCambio { get; set; }
        [Key]
        [Column("VersionID")]
        public long VersionId { get; set; }
    }
}